{"name": "Принятие заказа с невалидным ID курьера", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 400\n +  where 500 = <Response [500]>.status_code", "trace": "self = <tests.test_accept_order.TestAcceptOrder object at 0x00000284B94B7A80>, setup_courier_and_order = {'courier_id': 615723, 'login': 'nfosahwbuo', 'order_id': 546570, 'password': 'cxqkvfwree', ...}\n\n    @allure.title(\"Принятие заказа с невалидным ID курьера\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_accept_order_invalid_courier_id(self, setup_courier_and_order):\n        with allure.step(\"Попытаться принять заказ с невалидным ID курьера\"):\n            response = OrderApi.accept_order(\n                setup_courier_and_order[\"order_id\"],\n                \"invalid_id\"\n            )\n    \n        with allure.step(\"Проверить ошибку валидации\"):\n>           assert response.status_code == 400\nE           assert 500 == 400\nE            +  where 500 = <Response [500]>.status_code\n\ntests\\test_accept_order.py:48: AssertionError"}, "steps": [{"name": "Попытаться принять заказ с невалидным ID курьера", "status": "passed", "steps": [{"name": "Принять заказ 546570 курьером 'invalid_id'", "status": "passed", "parameters": [{"name": "order_id", "value": "546570"}, {"name": "courier_id", "value": "'invalid_id'"}], "start": 1758527531680, "stop": 1758527532058}], "start": 1758527531679, "stop": 1758527532058}, {"name": "Проверить ошибку валидации", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 400\n +  where 500 = <Response [500]>.status_code\n", "trace": "  File \"C:\\Users\\Пользователь\\sprint_7\\tests\\test_accept_order.py\", line 48, in test_accept_order_invalid_courier_id\n    assert response.status_code == 400\n"}, "start": 1758527532058, "stop": 1758527532058}], "start": 1758527531679, "stop": 1758527532059, "uuid": "b63be2da-3768-421d-8eaa-28fc0b7e8842", "historyId": "7340bb1811a392153b914aaffb7f586b", "testCaseId": "7340bb1811a392153b914aaffb7f586b", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_invalid_courier_id", "labels": [{"name": "epic", "value": "Order Management"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Accept Order API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "9396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}