{"uid":"7195bc4db01e3ed5","name":"Успешное принятие заказа","fullName":"tests.test_accept_order.TestAcceptOrder#test_accept_order_success","historyId":"bf3d90b089133297733d4bf073c72610","time":{"start":1758527525572,"stop":1758527526050,"duration":478},"status":"broken","statusMessage":"AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?","statusTrace":"self = <tests.test_accept_order.TestAcceptOrder object at 0x00000284B9516AD0>, setup_courier_and_order = {'courier_id': 615721, 'login': 'cxvurdxxdz', 'order_id': 501018, 'password': 'bwuvkzjiqa', ...}\n\n    @allure.title(\"Успешное принятие заказа\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_accept_order_success(self, setup_courier_and_order):\n        with allure.step(\"Принять заказ валидным курьером\"):\n            response = OrderApi.accept_order(\n                setup_courier_and_order[\"order_id\"],\n                setup_courier_and_order[\"courier_id\"]\n            )\n    \n        with allure.step(\"Проверить код ответа и тело\"):\n>           assert response.status_code == ExpectedResponses.SUCCESS_ACCEPT[\"code\"]\nE           AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?\n\ntests\\test_accept_order.py:22: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"setup_courier_and_order","time":{"start":1758527523577,"stop":1758527525570,"duration":1993},"status":"passed","steps":[{"name":"Логин курьера: 'cxvurdxxdz'","time":{"start":1758527524312,"stop":1758527524717,"duration":405},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"login","value":"'cxvurdxxdz'"},{"name":"password","value":"'bwuvkzjiqa'"}],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0},{"name":"Создать заказ","time":{"start":1758527524718,"stop":1758527525180,"duration":462},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"order_data","value":"{'firstName': 'Евгений', 'lastName': 'Косач', 'address': 'Ленинградский проспект, 53', 'metroStation': 10, 'phone': '+79181234564', 'rentTime': 6, 'deliveryDate': '2024-09-30', 'comment': 'Тестовый заказ'}"}],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0},{"name":"Получить заказ по треку 933148","time":{"start":1758527525180,"stop":1758527525570,"duration":390},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"track_id","value":"933148"}],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":3}],"testStage":{"status":"broken","statusMessage":"AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?","statusTrace":"self = <tests.test_accept_order.TestAcceptOrder object at 0x00000284B9516AD0>, setup_courier_and_order = {'courier_id': 615721, 'login': 'cxvurdxxdz', 'order_id': 501018, 'password': 'bwuvkzjiqa', ...}\n\n    @allure.title(\"Успешное принятие заказа\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_accept_order_success(self, setup_courier_and_order):\n        with allure.step(\"Принять заказ валидным курьером\"):\n            response = OrderApi.accept_order(\n                setup_courier_and_order[\"order_id\"],\n                setup_courier_and_order[\"courier_id\"]\n            )\n    \n        with allure.step(\"Проверить код ответа и тело\"):\n>           assert response.status_code == ExpectedResponses.SUCCESS_ACCEPT[\"code\"]\nE           AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?\n\ntests\\test_accept_order.py:22: AttributeError","steps":[{"name":"Принять заказ валидным курьером","time":{"start":1758527525572,"stop":1758527526048,"duration":476},"status":"passed","steps":[{"name":"Принять заказ 501018 курьером 615721","time":{"start":1758527525572,"stop":1758527526048,"duration":476},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"order_id","value":"501018"},{"name":"courier_id","value":"615721"}],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":1},{"name":"Проверить код ответа и тело","time":{"start":1758527526048,"stop":1758527526048,"duration":0},"status":"broken","statusMessage":"AttributeError: type object 'ExpectedResponses' has no attribute 'SUCCESS_ACCEPT'. Did you mean: 'SUCCESS_CREATE'?\n","statusTrace":"  File \"C:\\Users\\Пользователь\\sprint_7\\tests\\test_accept_order.py\", line 22, in test_accept_order_success\n    assert response.status_code == ExpectedResponses.SUCCESS_ACCEPT[\"code\"]\n","steps":[],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":3},"afterStages":[{"name":"setup_courier_and_order::0","time":{"start":1758527526107,"stop":1758527527030,"duration":923},"status":"passed","steps":[{"name":"Отменить заказ 933148","time":{"start":1758527526107,"stop":1758527526580,"duration":473},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"track_id","value":"933148"}],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0},{"name":"Удалить курьера 615721","time":{"start":1758527526582,"stop":1758527527023,"duration":441},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"courier_id","value":"615721"}],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0}],"attachments":[],"parameters":[],"hasContent":true,"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":2}],"labels":[{"name":"epic","value":"Order Management"},{"name":"feature","value":"Accept Order API"},{"name":"severity","value":"critical"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_accept_order"},{"name":"subSuite","value":"TestAcceptOrder"},{"name":"host","value":"HOME-PC"},{"name":"thread","value":"9396-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_accept_order"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"baec371247c9447e","status":"passed","time":{"start":1758386110921,"stop":1758386111331,"duration":410}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"tags":[]},"source":"7195bc4db01e3ed5.json","parameterValues":[]}